openapi: "3.0.0"
info:
  version: 1.0.0
  title: newTestFragmentOAS
paths: {}
components: 
  schemas:
    Person:
      type: object
      properties:
          name:
            type: string
          address:
            type: string
          email: 
            type: string
